// <auto-generated />
namespace Daybook.WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ADD_CURRENCYID_PLANNINGID_ActivityLog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADD_CURRENCYID_PLANNINGID_ActivityLog));
        
        string IMigrationMetadata.Id
        {
            get { return "201811211331261_ADD_CURRENCYID_PLANNINGID_ActivityLog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
